### ISSUE TITLE
Added translations to portugues from brazil

### ISSUE THREAD

**Issue by walissonaguirra** [imalitavakoli/learn-scrum#1]
Hi @imalitavakoli,
I would like to contribute to your post but I am getting the following error

![image](https://user-images.githubusercontent.com/53498071/188180422-8504ca7c-3dd6-4a53-aea4-2096ae89664f.png)

**Comment by imalitavakoli** [comment]
Thanks a lot for your interest and contribution to this tutorial repo 😊
But about the error that you're getting, I have no idea what is it about! I just googled your error, and found the following... Maybe it can help:
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

Again, thanks a lot ❤
